global:
  namespace: django-app

image:
  # Внутренний адрес для Kubernetes (временно используем IP вместо DNS, чтобы не перезапускать minikube)
  # IP может измениться при пересоздании сервиса - после перезапуска minikube лучше вернуть DNS-имя
  repository: "10.97.166.59:5000/django-app"
  tag: "latest"
  pullPolicy: Always

app:
  replicas: 2
  port: 8000
  env:
    DEBUG: "False"
    ALLOWED_HOSTS: "*"

ingress:
  enabled: true
  hosts:
    - host: django.local
      paths:
        - path: /
          pathType: Prefix

postgresql:
  enabled: true
  image:
    tag: "latest"
  auth:
    database: "django_app"
    username: "django_user"
    password: "postgres_password_123"
  primary:
    persistence:
      enabled: true
      size: 1Gi

monitoring:
  enabled: true
